#!/bin/sh

gcc -v 
uname -a
mkdir build
cd build

tar zxvf ../hts_engine_API-1.04.tar.gz
tar zxvf ../flite+hts_engine-1.01.tar.gz
tar zxvf ../hts_voice_cmu_us_arctic_slt-1.03.tar.gz
tar zxvf ../hts_voice_cstr_uk_female-1.0.tar.gz

export INSTALLDIR=`pwd`

cd hts_engine_API-1.04 
./configure --prefix=$INSTALLDIR
make
make install
cd ..

cd flite+hts_engine-1.01 
./configure --prefix=$INSTALLDIR --with-hts-engine-header-path=${INSTALLDIR}/include --with-hts-engine-library-path=${INSTALLDIR}/lib
make
make install


